FROM shoothzj/jdk13base:0.0.8
COPY ./projectDBServer-0.0.1-SNAPSHOT.jar /usr/src/projectDBServer-0.0.1-SNAPSHOT.jar
EXPOSE 8000
WORKDIR /usr/src/
CMD ["java", "-jar", "projectDBServer-0.0.1-SNAPSHOT.jar"]
