apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-todo
  name: spring-todo
  namespace: istio
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: spring-todo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-todo
  labels:
    app: spring-todo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-todo
  template:
    metadata:
      labels:
        app: spring-todo
    spec:
      containers:
      - image: hit1414/spring-msa-todo:latest
        name: spring-todo-pod
        env : 
        - name : LOGIN_IP
          value : "spring-login.istio.svc.cluster.local"
        - name : LOGIN_PORT
          value : "8000"
        - name : PROJECT_IP
          value : "spring-proj.istio.svc.cluster.local"
        - name : PROJECT_PORT
          value : "8000"
        - name : MAIN_IP
          value : "spring-main.istio.svc.cluster.local"
        - name : MAIN_PORT
          value : "8000"
        - name : TODO_IP
          value : "spring-todo.istio.svc.cluster.local"
        - name : TODO_PORT
          value : "8000"
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: regcred2


